on: [push, pull_request]

env:
  IMAGE_NAME: kiosk-nameplate

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag image